[workspace]
resolver = "2"

members = [
    "tutorial",
    "version-helper",

    "audio/audiofx",
    "audio/claxon",
    "audio/csound",
    "audio/lewton",
    "audio/speechmatics",
    "audio/spotify",

    "generic/file",
    "generic/originalbuffer",
    "generic/sodium",
    "generic/threadshare",
    "generic/inter",
    "generic/streamgrouper",
    "generic/gopbuffer",

    "mux/flavors",
    "mux/fmp4",
    "mux/mp4",

    "net/aws",
    "net/hlsmultivariantsink",
    "net/hlssink3",
    "net/mpegtslive",
    "net/ndi",
    "net/onvif",
    "net/raptorq",
    "net/reqwest",
    "net/relationmeta",
    "net/rtp",
    "net/rtsp",
    "net/webrtchttp",
    "net/webrtc",
    "net/webrtc/protocol",
    "net/webrtc/signalling",
    "net/quinn",

    "text/ahead",
    "text/json",
    "text/regex",
    "text/wrap",

    "utils/fallbackswitch",
    "utils/livesync",
    "utils/togglerecord",
    "utils/segmentclipper",
    "utils/tracers",
    "utils/uridecodepool",
    "utils/uriplaylistbin",

    "video/cdg",
    "video/closedcaption",
    "video/dav1d",
    "video/ffv1",
    "video/gif",
    "video/gtk4",
    "video/hsv",
    "video/png",
    "video/rav1e",
    "video/skia",
    "video/videofx",
    "video/vvdec",
    "video/webp",
]

default-members = [
    "version-helper",

    "audio/audiofx",
    "audio/claxon",
    "audio/lewton",

    "generic/originalbuffer",
    "generic/threadshare",
    "generic/inter",
    "generic/gopbuffer",
    "generic/streamgrouper",

    "mux/fmp4",
    "mux/mp4",

    "net/aws",
    "net/mpegtslive",
    "net/hlssink3",
    "net/onvif",
    "net/raptorq",
    "net/reqwest",
    "net/relationmeta",
    "net/rtp",
    "net/rtsp",
    "net/webrtchttp",
    "net/webrtc",
    "net/webrtc/protocol",
    "net/webrtc/signalling",
    "net/ndi",
    "net/quinn",

    "text/ahead",
    "text/json",
    "text/regex",
    "text/wrap",

    "utils/fallbackswitch",
    "utils/livesync",
    "utils/togglerecord",
    "utils/tracers",
    "utils/uridecodepool",
    "utils/uriplaylistbin",

    "video/cdg",
    "video/ffv1",
    "video/gif",
    "video/hsv",
    "video/png",
    "video/rav1e",
    "video/skia",
]

[profile.release]
lto = "thin"
opt-level = 3
debug = true
panic = 'unwind'

[profile.dev]
opt-level = 1
lto = "off"

[workspace.package]
version = "0.14.0-alpha.1"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
edition = "2021"
rust-version = "1.80"

[workspace.dependencies]
glib = { git = "https://github.com/gtk-rs/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa", features = [
  "use_glib",
] }
pango = { git = "https://github.com/gtk-rs/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
pangocairo = { git = "https://github.com/gtk-rs/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
gtk = { package = "gtk4", git = "https://github.com/gtk-rs/gtk4-rs", rev = "a7ea462cd1384f1730ff9a6bc066040225d22183", features = [
  "v4_6",
] }
gdk-wayland = { package = "gdk4-wayland", git = "https://github.com/gtk-rs/gtk4-rs", rev = "a7ea462cd1384f1730ff9a6bc066040225d22183", features = [
  "v4_4",
] }
gdk-x11 = { package = "gdk4-x11", git = "https://github.com/gtk-rs/gtk4-rs", rev = "a7ea462cd1384f1730ff9a6bc066040225d22183", features = [
  "v4_4",
] }
gdk-win32 = { package = "gdk4-win32", git = "https://github.com/gtk-rs/gtk4-rs", rev = "a7ea462cd1384f1730ff9a6bc066040225d22183", features = [
  "v4_4",
] }
gst = { package = "gstreamer", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-allocators = { package = "gstreamer-allocators", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-analytics = { package = "gstreamer-analytics", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-app = { package = "gstreamer-app", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-audio = { package = "gstreamer-audio", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-base = { package = "gstreamer-base", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-check = { package = "gstreamer-check", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-plugin-version-helper = { path = "./version-helper" }
gst-gl = { package = "gstreamer-gl", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-gl-egl = { package = "gstreamer-gl-egl", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-gl-wayland = { package = "gstreamer-gl-wayland", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-gl-x11 = { package = "gstreamer-gl-x11", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-net = { package = "gstreamer-net", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-pbutils = { package = "gstreamer-pbutils", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-rtp = { package = "gstreamer-rtp", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-sdp = { package = "gstreamer-sdp", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-utils = { package = "gstreamer-utils", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-validate = { package = "gstreamer-validate", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-video = { package = "gstreamer-video", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }
gst-webrtc = { package = "gstreamer-webrtc", git = "https://github.com/thiblahute/gstreamer-rs.git", branch = "sequence_1.26.0" }

[patch."https://github.com/gtk-rs/gtk-rs-core"]
glib = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
gio = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
cairo-rs = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa", features = ["use_glib"] }
pango = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
pangocairo = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
glib-sys = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
gio-sys = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
gobject-sys = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
cairo-sys-rs = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
pango-sys = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
pangocairo-sys = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
gdk-pixbuf = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
gdk-pixbuf-sys = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
graphene-rs = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
graphene-sys = { git = "https://github.com/thiblahute/gtk-rs-core", rev = "e6b43dc4d7cdb1ab62d6522c90807e6cd40973aa" }
